cmudig/draco2

docs/facts/examples.ipynb
draco/asp/hard.lp
draco/asp/helpers.lp
draco/spec.py
draco/tests/test_hard.py
draco/tests/test_spec_utils.py

* improve the unit tests for hard constraints with `no_violations` and `list_violations` helpers
* fixes #193
* simplify hard constraints by removing unnecessary entity declartions

fix: fix tests for hard constraints

---

.github/workflows/test.yml

from their [doc](https://black.readthedocs.io/en/stable/integrations/github_actions.html):
> We recommend the use of the @stable tag, but per version tags also exist if you prefer that. Note that the action’s version you select is independent of the version of Black the action will use.
The version of Black the action will use can be configured via version. 
Without specifying version, the default is using the latest(22.1.0)

ci: configure black version in ci

---

docs/api/draco.ipynb
docs/api/facts.ipynb
docs/api/run.ipynb
docs/api/schema.ipynb
docs/facts/intro.md
docs/facts/schema.md
docs/facts/task.md
docs/guide.ipynb
docs/intro.md
draco/draco.py
draco/run.py
draco/tests/test_constraints.py
draco/tests/test_hard.py
draco/tests/test_soft.py
draco/weights.py

- fix various typos in the docs and source files
- add hyperlinks in docs where sensible
- make the docs overall more pleasant to read
The [documentation](https://dig.cmu.edu/draco2/api/draco.html) of the `draco.Draco` class is pretty verbose thanks to the automatic default value expansion of Sphinx. I think it would make sense to spawn a new issue for its fix (I would be glad to contribute).  I have two approaches on my mind for the fix:
1. Tap into the Jupyter Book configuration and register a Sphinx function to remove the default value from the expansion, as suggested by [this StackOverflow answer](https://stackoverflow.com/a/69865409/14457639)
2. Create a custom `__repr__` and/or `__str__` in `programs.Program` and `weights.Weights` to have a more compact value representation, …

docs: improve docs

---

.github/workflows/test.yml
docs/_config.yml
docs/api/draco.ipynb
docs/conf.py

- Disable the expansion of default values in docstrings
- Fix the looks of the [Draco Class Documentation section](https://dig.cmu.edu/draco2/api/draco.html#class-documentation)
- Found a solution which is the cleanest one imho: there is an [official `autodoc` config](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_preserve_defaults) for this

docs: no default value expansion

---

.github/workflows/book.yml

- handle the installation and caching of `poetry` in `book.yml` in the same way as in `test.yml` (introduced in #343)
- might prevent the build issue faced in f294f41
- achieving the same thing across GitHub-Actions in the same way would be sensible

build: uniform `poetry` installation and caching across gh-actions

---

README.md

Fixes typos and adds a hyperlink to Clingo in `README.md`.

docs: fix typos in `README.md`

---

Makefile
docs/_toc.yml
docs/api/server.md
docs/applications/server.md
draco/server/draco_api.py
draco/server/routers/base.py
draco/server/routers/clingo.py
draco/server/routers/draco.py
draco/server/routers/utility.py
pyproject.toml

- Document the server module
- Add hands-on examples
- I modified the router API slightly to provide a better developer experience when customizing existing routes. Now we set route `prefix` and `tags` internally by default.
closes #422

docs: document server API and applications

---

.dockerignore
Dockerfile

- Fix missing Binder modules
While Binder supports [various simpler configuration files](https://mybinder.readthedocs.io/en/latest/using/config_files.html), using a `Dockerfile` has the most benefits for us IMHO.
- If we wanted to use a `requirements.txt` we would need to constantly sync between `pyproject.toml` and `requirements.txt` using `poetry export`. While this would be possible using a GH action, it would have been more work than the committed `Dockerfile`
- Using any of the other config options would not fit into our Poetry setup
- With the custom Docker env I declared, opening the terminal in Binder's Jupyter Lab will give access to the same dev environment we are using. That is, executing `make` targets is also possible.
I had to add Draco 2 as a pip package to the Docker …

fix: binder requirements (#430)

---

draco/renderer/altair/types.py
draco/server/draco_api.py

Fixes some warnings encountered during `make book`.
The syntax highlighting is back for me locally after running `make book-serve`.
Closes #477

docs: bring back syntax highlighting (#477)

---

CONTRIBUTING.md
Dockerfile
Makefile

As we are emphasizing the tooling and the DX around Draco 2, I thought it would be useful to have a copy-paste-ready command that anyone can execute with Docker, to start all the components locally.

chore: update Python version in `Dockerfile` & document dev with docker

---

.github/workflows/test.yml
Dockerfile
Makefile

The `test-docker` job I added in this PR executes `make all` inside a docker container based on our root `Dockerfile`. If the `test-docker` job succeeds along with the other, non-dockerized checks, we can conclude that the dockerized environment works as expected.
The job is expected to fail if any of the other jobs (`lint` or `test`) fail.
I had to update from debian buster to bullseye, since I kept getting a Python seg fault inside the container running on the GH runner. The error disappeared after upgrading to bullseye.
Closes #483

ci: test `Dockerfile` (#483)

---

.github/workflows/build.yml

We specify the JupyterLite deps in that group.

fix: use `poetry install --with web` to build docs

---

poetry.lock
pyproject.toml

Syncs with the version used by pre-commit, added in 85ca92d

chore: bump ruff to `0.0.253`

---

.github/workflows/build.yml

The implementation builds on top of the [Deploy Static HTML](https://github.com/cmudig/draco2/new/main?filename=.github%2Fworkflows%2Fstatic.yml) example action.
I could not run the action on this branch, since protection rules seem to allow gh pages deployment only through the `main` branch.

ci: use artifacts for gh pages build (#522)

---

pyodide/build.py

Needed so that the repo Python version and the web Python version are in sync. To be reverted as soon as google/pytype#1308 is addressed and we can bump our repo Python version to `3.11`.

chore: set Pyodide version to `0.22.1`

---

.github/workflows/build.yml
docs/_config.yml

Should fix this issue we have in the current docs:

ci: install `clingo` for `jupyter-book` build

---

docs/_config.yml

ci: increase `jupyter-book` execution timeout

---

pyproject.toml

chore: add language tag for Python 3.11

---

Makefile
poetry.lock
pyodide/build.py
pyodide/cache_dl.py
pyodide/packages/annotated-types/meta.yaml
pyodide/packages/pydantic-core/meta.yaml
pyodide/packages/pydantic/meta.yaml
pyproject.toml

**⚠️ The renderer cannot be used via JupyterLite at the moment, meaning that no actual visuals can be displayed when getting started with Draco through the browser. This PR adds a fix.**
This is caused by a regression introduced in #673 after we migrated to Pydantic 2: we migrated the pure-python project dependency, but not the Pyodide dependency.
We should add some tests around our WASM distribution soon.
To support Pydantic 2 in Pyodide I had to add Rust as a dependency to the Pyodide build environment, as https://github.com/pydantic/pydantic-core is written in Rust.
Our latest Pyodide distribution is always hosted under https://dig.cmu.edu/draco2/jupyterlite/static/pyodide. Instead of rebuilding each artifact each time, we can do a diffing based on 
- the version of the latest, …

ci: adjust Pyodide deps and retrieve prebuilt artifacts

---

jupyterlite/lite-dir/jupyter-lite.json
poetry.lock
pyproject.toml

We lost it when migrating to jupyterlite `0.2.0` in #758

fix: make jupyterlite work with pyodide again

---

poetry.lock
pyproject.toml

Also adds `jupyterlite-pyodide-kernel` as a dependency so that the kernel is recognized.
Without doing so, the Pyodide distribution we build will never be included in the JupyterLite output, therefore it is excluded from our GitHub Pages deployment.

chore: update `jupyterlite` and explicitly list Pyodide kernel

---

.dockerignore
.gitignore
.vscode/settings.json
Makefile
draco/server/models/clingo.py
draco/server/models/draco.py
draco/server/models/renderer.py
draco/server/models/utility.py
pyproject.toml
uv.lock

As communicated by pytype [officially](https://github.com/google/pytype/commit/762b86d07d336613b4dfcc9f15ce9c4b730dbc02), they have no plans to support any Python version above 3.12. As even their Python 3.12 coverage is suboptimal (we are forced to add seemingly unnecessary casts, explicit hints, etc. to satisfy the checker) moving away from it seems reasonable.
As a follow-up of this PR we should consider moving to [Pyrefly](https://pyrefly.org/) and/or wait for [ty](https://github.com/astral-sh/ty) to become stable.

chore: drop `pytype`

---

.github/workflows/test.yml
Makefile

Currently our CI flows take ~13 minutes as the in-Docker build of JupyterBook docs take a long time due to notebook executions.
The `test-docker` job's sole responsibility is to verify that the in-Docker env is functional, running only the lint, test, grounding, etc. `make` targets should also be sufficient.
Making this change brings our CI time from ~13 minutes to ~1 minute.

ci: reduce workflow time by 10x
